one_wire:
  - platform: gpio
    setup_priority: 1000 #https://github.com/esphome/issues/issues/5983
    pin: ${onewire_pin}
    id: ${id_prefix}dallas_bus

# ============================================
# 1-Wire Scan Button & Results
# ============================================
button:
  - platform: template
    name: "Scan 1-Wire Bus"
    icon: mdi:magnify
    entity_category: diagnostic
    on_press:
      - lambda: |-
          // Search for devices
          auto devices = id(${id_prefix}dallas_bus).get_devices();
          
          std::string result = "";
          int count = 0;
          
          for (auto &device : devices) {
            count++;
            char addr[32];
            sprintf(addr, "0x%016llX", device);
            if (count > 1) result += "\n";
            result += std::to_string(count) + ": " + addr;
          }
          
          if (count == 0) {
            result = "No devices found";
          } else {
            result = "Found " + std::to_string(count) + " device(s):\n" + result;
          }
          
          id(${id_prefix}onewire_scan_result).publish_state(result);
          ESP_LOGI("onewire", "%s", result.c_str());
    id: ${id_prefix}dallas_bus_test_bt
    web_server:
      sorting_group_id: sorting_group_debug

text_sensor:
  - platform: template
    name: "1-Wire Scan Result"
    id: ${id_prefix}onewire_scan_result
    icon: mdi:chip
    entity_category: diagnostic
    web_server:
      sorting_group_id: sorting_group_debug

# ============================================
# Supply (Input) Temperature Sensor
# ============================================
sensor:
  - platform: dallas_temp
    setup_priority: -100 #https://github.com/esphome/issues/issues/5983
    address: ${dallasaddress_input}
    name: Heating circuit Input temp
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-high"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 2
    update_interval: 60s
    id: ${id_prefix}dallas_input_temp
    # To calibrate: add filter below (negative = sensor reads too high)
    # filters:
    #   - offset: -2.0
    web_server:
      sorting_group_id: sorting_group_status
    
  # ============================================
  # Manifold Return (Output) Temperature Sensor
  # ============================================
  - platform: dallas_temp
    setup_priority: -100 #https://github.com/esphome/issues/issues/5983
    address: ${dallasaddress_output}
    name: Heating circuit Output temp
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-low"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 2
    update_interval: 60s
    id: ${id_prefix}dallas_output_temp
    web_server:
      sorting_group_id: sorting_group_status

  # ============================================
  # Extra Temperature Sensor (for identification/testing)
  # ============================================
  - platform: dallas_temp
    setup_priority: -100
    address: ${dallasaddress_extra}
    name: Extra temp sensor
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 2
    update_interval: 60s
    id: ${id_prefix}dallas_extra_temp
    web_server:
      sorting_group_id: sorting_group_status
