# ============================================
# MQTT Integration for Ecodan Heat Pump
# ============================================
# Loose coupling between floor heating controllers and Ecodan
# Controllers work independently but can request flow temp adjustments
#
# Published topics (from this controller):
#   floor_heating/controller_{id}/online
#   floor_heating/controller_{id}/heating_demand
#   floor_heating/controller_{id}/avg_valve_position
#   floor_heating/controller_{id}/avg_return_temp
#   floor_heating/controller_{id}/zone_count
#   floor_heating/controller_{id}/flow_temp_request
#
# Subscribed topics:
#   ecodan/flow_temperature
#   ecodan/outdoor_temperature
#   floor_heating/controller_+/avg_valve_position (other controllers)
#   floor_heating/controller_+/heating_demand (other controllers)

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant
  
  # Last Will and Testament for availability
  birth_message:
    topic: floor_heating/controller_${controller_id}/online
    payload: "true"
    retain: true
  will_message:
    topic: floor_heating/controller_${controller_id}/online
    payload: "false"
    retain: true
  
  on_message:
    # ============================================
    # Receive flow temperature from Ecodan
    # ============================================
    - topic: ecodan/flow_temperature
      then:
        - lambda: |-
            float flow_temp = atof(x.c_str());
            id(${id_prefix}ecodan_flow_temp) = flow_temp;
            ESP_LOGD("mqtt_ecodan", "Received Ecodan flow temp: %.1f°C", flow_temp);
    
    # ============================================
    # Receive outdoor temperature from Ecodan
    # ============================================
    - topic: ecodan/outdoor_temperature
      then:
        - lambda: |-
            float outdoor_temp = atof(x.c_str());
            id(${id_prefix}ecodan_outdoor_temp) = outdoor_temp;
            ESP_LOGD("mqtt_ecodan", "Received outdoor temp: %.1f°C", outdoor_temp);
    
    # ============================================
    # Receive other controller's valve position
    # ============================================
    - topic: floor_heating/controller_+/avg_valve_position
      then:
        - lambda: |-
            // Extract controller ID from topic
            std::string topic_str = topic;
            size_t start = topic_str.find("controller_") + 11;
            size_t end = topic_str.find("/", start);
            std::string ctrl_id = topic_str.substr(start, end - start);
            
            // Don't process our own messages
            if (ctrl_id == "${controller_id}") return;
            
            float other_avg = atof(x.c_str());
            id(${id_prefix}other_controller_avg_position) = other_avg;
            ESP_LOGD("mqtt_ecodan", "Other controller %s avg position: %.1f%%", ctrl_id.c_str(), other_avg);
    
    # ============================================
    # Receive other controller's heating demand
    # ============================================
    - topic: floor_heating/controller_+/heating_demand
      then:
        - lambda: |-
            std::string topic_str = topic;
            size_t start = topic_str.find("controller_") + 11;
            size_t end = topic_str.find("/", start);
            std::string ctrl_id = topic_str.substr(start, end - start);
            
            if (ctrl_id == "${controller_id}") return;
            
            bool other_demand = (x == "true" || x == "1");
            id(${id_prefix}other_controller_has_demand) = other_demand;
            ESP_LOGD("mqtt_ecodan", "Other controller %s demand: %s", ctrl_id.c_str(), other_demand ? "true" : "false");

globals:
  # Received from Ecodan
  - id: ${id_prefix}ecodan_flow_temp
    type: float
    restore_value: no
    initial_value: '35.0'
  - id: ${id_prefix}ecodan_outdoor_temp
    type: float
    restore_value: no
    initial_value: '10.0'
  
  # Other controller state
  - id: ${id_prefix}other_controller_avg_position
    type: float
    restore_value: no
    initial_value: '50.0'
  - id: ${id_prefix}other_controller_has_demand
    type: bool
    restore_value: no
    initial_value: 'false'
  
  # Flow temp request tracking
  - id: ${id_prefix}last_flow_temp_request
    type: int
    restore_value: no
    initial_value: '0'
  - id: ${id_prefix}low_demand_duration
    type: int
    restore_value: no
    initial_value: '0'
  - id: ${id_prefix}high_demand_duration
    type: int
    restore_value: no
    initial_value: '0'

# ============================================
# MQTT Publishing Sensors
# ============================================
sensor:
  - platform: template
    name: "Ecodan Flow Temp"
    id: ${id_prefix}ecodan_flow_temp_sensor
    icon: "mdi:thermometer"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    lambda: |-
      return id(${id_prefix}ecodan_flow_temp);
    update_interval: 60s
    
  - platform: template
    name: "Ecodan Outdoor Temp"
    id: ${id_prefix}ecodan_outdoor_temp_sensor
    icon: "mdi:thermometer"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    lambda: |-
      return id(${id_prefix}ecodan_outdoor_temp);
    update_interval: 60s

  - platform: template
    name: "Other Controller Avg Position"
    id: ${id_prefix}other_controller_avg_sensor
    icon: "mdi:valve"
    unit_of_measurement: "%"
    accuracy_decimals: 1
    lambda: |-
      return id(${id_prefix}other_controller_avg_position);
    update_interval: 30s

binary_sensor:
  - platform: template
    name: "Heating Demand"
    id: ${id_prefix}heating_demand
    icon: "mdi:fire"
    lambda: |-
      // Check if any zone is in DEMAND state (state == 2)
      if (id(${id_prefix}zone_1_state) == 2) return true;
      if (id(${id_prefix}zone_2_state) == 2) return true;
      if (id(${id_prefix}zone_3_state) == 2) return true;
      if (id(${id_prefix}zone_4_state) == 2) return true;
      if (id(${id_prefix}zone_5_state) == 2) return true;
      if (id(${id_prefix}zone_6_state) == 2) return true;
      if (id(${id_prefix}zone_7_state) == 2) return true;
      if (id(${id_prefix}zone_8_state) == 2) return true;
      return false;
    on_state:
      then:
        - mqtt.publish:
            topic: floor_heating/controller_${controller_id}/heating_demand
            payload: !lambda 'return x ? "true" : "false";'
            retain: true

  - platform: template
    name: "Other Controller Has Demand"
    id: ${id_prefix}other_controller_demand_sensor
    icon: "mdi:fire"
    lambda: |-
      return id(${id_prefix}other_controller_has_demand);

switch:
  - platform: template
    name: "Flow Temp Request Enabled"
    id: ${id_prefix}flow_temp_request_enabled
    icon: "mdi:thermometer-auto"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

text_sensor:
  - platform: template
    name: "Flow Temp Request"
    id: ${id_prefix}flow_temp_request_sensor
    icon: "mdi:thermometer-chevron-up"
    lambda: |-
      int request = id(${id_prefix}last_flow_temp_request);
      if (request == 0) return {"No change"};
      if (request > 0) return {"+" + to_string(request) + "°C"};
      return {to_string(request) + "°C"};

# ============================================
# MQTT Publishing Interval
# ============================================
interval:
  - interval: 30s
    then:
      - mqtt.publish:
          topic: floor_heating/controller_${controller_id}/avg_valve_position
          payload: !lambda 'return to_string(id(${id_prefix}avg_valve_position).state);'
          retain: true
      - mqtt.publish:
          topic: floor_heating/controller_${controller_id}/avg_return_temp
          payload: !lambda 'return to_string(id(${id_prefix}avg_return_temp).state);'
          retain: true
      - mqtt.publish:
          topic: floor_heating/controller_${controller_id}/zone_count
          payload: !lambda 'return to_string((int)id(${id_prefix}active_return_sensors).state);'
          retain: true

  # ============================================
  # Flow Temperature Request Logic (every 5 min)
  # ============================================
  - interval: 5min
    then:
      - lambda: |-
          if (!id(${id_prefix}flow_temp_request_enabled).state) {
            id(${id_prefix}last_flow_temp_request) = 0;
            return;
          }
          
          float my_avg = id(${id_prefix}avg_valve_position).state;
          float other_avg = id(${id_prefix}other_controller_avg_position);
          bool other_has_demand = id(${id_prefix}other_controller_has_demand);
          
          // Calculate system-wide average (simple average for 2 controllers)
          // In real implementation, weight by zone count
          float system_avg = (my_avg + other_avg) / 2.0;
          
          ESP_LOGD("mqtt_ecodan", "Flow temp check: my_avg=%.1f%%, other_avg=%.1f%%, system_avg=%.1f%%",
                   my_avg, other_avg, system_avg);
          
          int request = 0;
          
          // Flow temperature adjustment based on system average
          // Goal: Keep system average at 50-80% for optimal heat pump COP
          if (system_avg < 30) {
            // All zones nearly satisfied, reduce output
            id(${id_prefix}low_demand_duration) += 5;
            id(${id_prefix}high_demand_duration) = 0;
            if (id(${id_prefix}low_demand_duration) >= 15) {
              request = -2;
            }
          } else if (system_avg < 50) {
            // Low demand, can lower temperature
            id(${id_prefix}low_demand_duration) += 5;
            id(${id_prefix}high_demand_duration) = 0;
            if (id(${id_prefix}low_demand_duration) >= 15) {
              request = -1;
            }
          } else if (system_avg <= 80) {
            // Optimal range - no change
            id(${id_prefix}low_demand_duration) = 0;
            id(${id_prefix}high_demand_duration) = 0;
            request = 0;
          } else if (system_avg <= 90) {
            // High demand, need more heat
            id(${id_prefix}high_demand_duration) += 5;
            id(${id_prefix}low_demand_duration) = 0;
            if (id(${id_prefix}high_demand_duration) >= 15) {
              request = 1;
            }
          } else {
            // Valves maxed out, insufficient heat
            id(${id_prefix}high_demand_duration) += 5;
            id(${id_prefix}low_demand_duration) = 0;
            if (id(${id_prefix}high_demand_duration) >= 15) {
              request = 2;
            }
          }
          
          // Only publish if request changed or is non-zero
          if (request != id(${id_prefix}last_flow_temp_request) || request != 0) {
            id(${id_prefix}last_flow_temp_request) = request;
            
            // Publish flow temp request
            id(mqtt_client).publish("floor_heating/controller_${controller_id}/flow_temp_request", 
                                    to_string(request));
            
            // Also publish to system topic for Ecodan to see
            id(mqtt_client).publish("floor_heating/system/flow_temp_adjustment", 
                                    to_string(request));
            
            ESP_LOGI("mqtt_ecodan", "Flow temp request: %+d°C (system_avg=%.1f%%)", request, system_avg);
          }
